# Generated by Django 2.2.3 on 2019-07-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_stocks_time_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='time_series',
        ),
    ]
